---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 1

provisioner:
  name: chef_zero
  require_chef_omnibus: "<%= ENV.has_key?('CHEF_VERSION') ? ENV['CHEF_VERSION'] : true %>"

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-6.9
  - name: centos-7.5
  - name: oracle-6.9
  - name: oracle-7.5
    driver_config:
      box: bento/oracle-7.5

suites:
  - name: base
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      # This seems to be automatically installed by RHEL / CentOS / Oracle,
      # but not by Debian, which causes the Debian tests to fail because they
      # are looking for auditd
      - recipe[system_core::auditd]
      - recipe[system_core::repos]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
      - recipe[system_core::ssh]
      - recipe[system_core::logrotate]
      - recipe[system_core::user_ssh]
    attributes:
      system_core:
        ssh:
          authorized_keys:
            root:
              public_key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlvaL0I0HWNE/RblFscFWhjXDwX6UaMBLtG5YdbHHSc1QQO+W+kV15q3T7WnED6In+aK423OzMTk/0/UZrchlxa2KCRNSnRrqViTZZ1XUXwEXqCnBQ9O1El93AAaE73suB9kYfeO105D5AgTTmf41HDc4YAxZtoAOt2KdI2GF7+7IfheI54aWSldmQesfqNloY+ivYIOhyEIwXuO9RS2BEbrFoxuVfOcz62AGcFz07EsALWGNzr4ngT6pe8vCbV5s/f0cDk5z9XZ4Wk2uQI7NQuLkSOmokU3QqZhOYJUjjTdq8VrjARWdF7K5N0/LQ/Wyx6Tgy+XRavnmj/SMhaKd"
              user: 'root'
          user_config:
            root:
              hosts:
                \*:
                  SendEnv: "LANG LC_*"
                  ForwardAgent: "yes"
                  UserKnownHostsFile: "/dev/null"
                  StrictHostKeyChecking: "no"
              keys:
                id_rsa:
                  owner: root
                  ssh_key_bucket: "<%= ENV['SSH_KEY_BUCKET'] %>"
                  ssh_key_path: "<%= ENV.key?('ROOT_SSH_KEY_PATH') ? ENV['ROOT_SSH_KEY_PATH'] : 'ssh-keys/root' %>"
        aws:
          profiles:
            default:
              output_format: "json"
              region: "<%= ENV.key('AWS_REGION') ? ENV['AWS_REGION'] : 'us-east-1' %>"
              access_key: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
              secret_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  - name: logging
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rsyslog]
      - recipe[system_core::logrotate]
      - recipe[system_core::papertrail]
      - recipe[system_core::papertrail_remote]
      - recipe[logrotate::default]
    verifier:
      attributes:
        papertrail_host: '@@log.example.com:11111'
    attributes:
      system_core:
        papertrail:
          enabled: true
          remote_host: '@@log.example.com:11111'
          remote_syslog2:
            files:
              - /some/file/without-tags:
              - /some/file/with-tag: 'test'
  - name: ruby
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rbenv]
  - name: altdomain
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
    verifier:
      attributes:
        default_domain: linux.alt.org
    attributes:
      system_core:
        aws:
          profiles:
            default:
              output_format: "json"
              region: "<%= ENV.key('AWS_REGION') ? ENV['AWS_REGION'] : 'us-east-1' %>"
              access_key: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
              secret_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
        domain: "linux.alt.org"
