---
driver:
  name: vagrant

transport: dokken
provisioner:
  name: dokken

suites:
  - name: default-centos6
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]

  - name: default-centos7
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
  - name: base-centos6
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::rootkey]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
      - recipe[system_core::ssh]
      - recipe[system_core::logrotate]
  - name: base-centos7
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::rootkey]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
      - recipe[system_core::ssh]
      - recipe[system_core::logrotate]
  - name: logging-centos6
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rsyslog]
      - recipe[system_core::logrotate]
      - recipe[system_core::papertrail]
      - recipe[logrotate::default]
  - name: logging-centos7
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rsyslog]
      - recipe[system_core::logrotate]
      - recipe[system_core::papertrail]
      - recipe[logrotate::default]
  - name: ruby-centos6
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rbenv]
  - name: ruby-centos7
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rbenv]
  - name: altdomain-centos6
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::rootkey]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
      - recipe[system_core::ssh]
      - recipe[system_core::logrotate]
    attributes:
      system_core:
        domain: "linux.alt.org"
  - name: altdomain-centos7
    driver:
      name: dokken
      chef_version: current
      privileged: true
      volumes: [
        '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
      ]
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /sbin/init
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::rootkey]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
      - recipe[system_core::ssh]
      - recipe[system_core::logrotate]
    attributes:
      system_core:
        domain: "linux.alt.org"
