---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  product_name: chef
  product_version: "<%= ENV.has_key?('CHEF_VERSION') ? ENV['CHEF_VERSION'] : 17 %>"
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  chef_license: accept
  # log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: oracle-7.7
  - name: oracle-8.1

suites:
  - name: base
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      # This seems to be automatically installed by RHEL / CentOS / Oracle,
      # but not by Debian, which causes the Debian tests to fail because they
      # are looking for auditd
      - recipe[system_core::auditd]
      - recipe[system_core::repos]
      - recipe[system_core::awscli]
      - recipe[system_core::bash]
      - recipe[system_core::postfix]
      - recipe[system_core::ntp]
      - recipe[system_core::selinux]
      - recipe[system_core::ssh]
      - recipe[system_core::sudo]
      - recipe[system_core::logrotate]
      - recipe[system_core::user_ssh]
    attributes:
      system_core:
        ssh:
          user_config:
            root:
              hosts:
                \*:
                  SendEnv: "LANG LC_*"
                  ForwardAgent: "yes"
                  UserKnownHostsFile: "/dev/null"
                  StrictHostKeyChecking: "no"
  - name: logging
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::rsyslog]
      - recipe[system_core::logrotate]
      - recipe[system_core::papertrail]
      - recipe[system_core::papertrail_remote]
      - recipe[logrotate::default]
    verifier:
      attributes:
        papertrail_host: '@@log.example.com:11111'
    attributes:
      system_core:
        papertrail:
          enabled: true
          remote_host: '@@log.example.com:11111'
          remote_syslog2:
            files:
              /some/file/without-tags:
              /some/file/with-tag: 'test'
              /some/second/file/with-tag: 'test'
              /some/third/file/with-tag: 'test'
              /some/second/file/without-tags:
  - name: ruby
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
      - recipe[system_core::rbenv]
  - name: altdomain
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[system_core::default]
      - recipe[system_core::repos]
    verifier:
      attributes:
        default_domain: linux.alt.org
    attributes:
      system_core:
        domain: "linux.alt.org"
