AllCops:
  Exclude:
    - 'Vagrantfile'
    - vendor/**/*
  DisplayCopNames: true

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'metadata.rb'

Metrics/BlockLength:
  Max: 35

Layout/LineLength:
  Max: 180

Style/Encoding:
  Enabled: false

# TODO: Enable this in the future.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
