---
sudo: false
language: ruby
bundler_args: "--without development"
dist: trusty
cache: bundler

rvm: 2.5.5

before_install:
  - gem update --system # see https://github.com/bundler/bundler/issues/5357

matrix:
  include:
    - env: UNIT_AND_LINT=1
      script:
        - bundle exec rake lint spec
