name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Setup Ruby
      env:
        UNIT_AND_LINT: "1"
      run: |
        gem update --system
        gem install bundler --version=1.17
        bundle install --jobs 4 --retry 3
    - name: Code Linting
      env:
        UNIT_AND_LINT: "1"
      run: |
        bundle exec rake lint
    - name: Unit Tests
      env:
        UNIT_AND_LINT: "1"
      run: |
        bundle exec rake spec
    # - name: Integration Tests
    #   env:
    #     UNIT_AND_LINT: "1"
    #   run: |
    #     bundle exec rake kitchen-ec2
