name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Setup Ruby Components
      env:
        UNIT_AND_LINT: "1"
      run: |
        gem update --system
        gem install bundler
        bundle install
    - name: Code Linting
      env:
        UNIT_AND_LINT: "1"
      run: |
        bundle exec rake lint
    - name: Unit Tests
      env:
        UNIT_AND_LINT: "1"
      run: |
        bundle exec rake spec
    - name: Integration Tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_REGION: "us-east-1"
        AWS_SSH_KEY_ID: "${{ secrets.AWS_SSH_KEY_ID }}"
        AWS_SSH_PRIVATE_KEY: "${{ secrets.AWS_SSH_PRIVATE_KEY }}"
        DRIVER_SECURITY_GROUP_IDS: "${{ secrets.DRIVER_SECURITY_GROUP_IDS }}"
        INSTANCE: "base-oracle-7"
        KITCHEN_YAML: ".kitchen-ec2.yml"
        PLATFORMS_ORACLE7_DRIVER_IMAGEID: "ami-01dcdbd83c7e846ec"
        PLATFORMS_ORACLE8_DRIVER_IMAGEID: "ami-047627086234fbbe7"
        SSH_KEY_BUCKET: "${{ secrets.SSH_KEY_BUCKET }}"
        SSH_PRIVATE_KEY: "/home/runner/.ssh/chef-test-kitchen.pem"
        UNIT_AND_LINT: "1"
      # To test this locally, use Docker:
      # AWS_DEFAULT_REGION="us-east-1"
      # SGID="$(aws ec2 describe-security-groups --region $AWS_DEFAULT_REGION | jq -r '.SecurityGroups[] | select(.Tags != null) | select(.Tags[].Key == "ChefTestKitchen" and .Tags[].Value == "true") | .GroupId')"
      # AMIID="$(aws ec2 describe-images --owners 131827586825 --filters 'Name=is-public,Values=true,Name=virtualization-type,Values=hvm' --region $AWS_DEFAULT_REGION | jq -r '.Images[] | select(.Name | test("^OL7.6")) | .ImageId')"
      # docker run \
      #   -e DRIVER_SECURITY_GROUP_IDS="${SGID}" \
      #   -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
      #   -e KITCHEN_YAML=.kitchen-ec2.yml \
      #   -e SSH_PRIVATE_KEY=/root/.ssh/chef-test-kitchen.pem \
      #   -e AWS_SSH_PRIVATE_KEY="$(cat ~/.ssh/chef-test-kitchen.pem)" \
      #   -e PLATFORMS_ORACLE76_DRIVER_IMAGEID=$AMIID \
      #   -e CI=true -e INSTANCE=base-oracle-7 \
      #   -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
      #   -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
      #   -e AWS_SSH_KEY_ID=chef-test-kitchen \
      #   -v /Users/justin/.ssh:/root/.ssh \
      #   -v $(pwd)/..:/chef \
      #   -it ruby:3.0 /bin/bash
      run: |
        env | egrep -v '^AWS_(ACCESS_KEY|SECRET_ACCESS_KEY|AWS_SSH_PRIVATE_KEY)' | sort
        test -d ~/.ssh || mkdir ~/.ssh
        chmod 0700 ~/.ssh
        printf '%s' "$AWS_SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/chef-test-kitchen.pem
        printf '\n' >> ~/.ssh/chef-test-kitchen.pem
        chmod 0600 ~/.ssh/chef-test-kitchen.pem
        printf ' =====  SSH Key =====\n'
        ls -latr ~/.ssh/
        head -2 ~/.ssh/chef-test-kitchen.pem
        printf ' =====  END SSH Key =====\n'
        bundle exec rake kitchen_ec2
