name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Build and test with Rake
      env:
        UNIT_AND_LINT: "1"
      run: |
        gem update --system
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake lint spec
